"""Compile uploaded Excalidraw/SVG into ExcalidrawScene Manim code."""

from __future__ import annotations

import ast
import re
from pathlib import Path
from typing import Any

from app.excalidraw_parser import describe_drawing_animation_units

SCENE_CLASS = "ExcalidrawScene"
DEFAULT_RUN_TIME = 7.0
DEFAULT_HOLD_TIME = 1.25


def _esc_path(path: Path) -> str:
    return str(path.resolve()).replace("\\", "\\\\")


def _esc_comment(text: str) -> str:
    return text.replace("\n", " ").strip()


def _unit_label(unit: dict[str, Any]) -> str:
    kind = str(unit.get("kind") or "shape")
    label = _esc_comment(str(unit.get("label") or f"Unit {unit.get('index')}"))
    return f"{label} ({kind})"


def _format_unit_catalog(pages: list[dict[str, Any]]) -> str:
    if not pages:
        return ""
    lines = ["        # Unit index catalog — each page lists animatable elements by index."]
    for page in pages:
        page_index = int(page.get("page_index", 0))
        page_name = _esc_comment(str(page.get("page_name") or f"Page {page_index + 1}"))
        lines.append(f"        # Page {page_index} \"{page_name}\":")
        for unit in page.get("units") or []:
            idx = int(unit.get("index", 0))
            lines.append(f"        #   [{idx}] {_unit_label(unit)}")
    return "\n".join(lines)


def _format_page_sequences(
    pages: list[dict[str, Any]],
    page_sequences: dict[int, list[int]] | None,
) -> str:
    if not page_sequences:
        return "            {},"

    units_by_page: dict[int, dict[int, dict[str, Any]]] = {}
    names_by_page: dict[int, str] = {}
    for page in pages:
        page_index = int(page.get("page_index", 0))
        names_by_page[page_index] = _esc_comment(str(page.get("page_name") or f"Page {page_index + 1}"))
        units_by_page[page_index] = {
            int(unit.get("index", 0)): unit for unit in (page.get("units") or [])
        }

    lines = ["            {"]
    for page_index in sorted(page_sequences):
        order = [int(v) for v in page_sequences[page_index]]
        if not order:
            continue
        page_name = names_by_page.get(page_index, f"Page {page_index + 1}")
        lines.append(f"                # Page {page_index} \"{page_name}\" — top draws first")
        lines.append(f"                {page_index}: [")
        for step, unit_index in enumerate(order, start=1):
            unit = units_by_page.get(page_index, {}).get(unit_index)
            if unit:
                note = _unit_label(unit)
            else:
                note = f"unit {unit_index}"
            lines.append(f"                    {unit_index},  # {step}. {note}")
        lines.append("                ],")
    lines.append("            },")
    return "\n".join(lines)


def starter_excalidraw_scene() -> str:
    return f'''"""Excalidraw animation — generated by Manimations Studio."""

from manim import *


class {SCENE_CLASS}(Scene):
    def construct(self):
        self.camera.background_color = BLACK
        hint = Text("Upload Excalidraw SVG and click Generate", color=WHITE, font_size=32)
        self.play(FadeIn(hint), run_time=0.8)
        self.wait(2.0)
        self.play(FadeOut(hint), run_time=0.6)
'''


def compile_excalidraw_scene(
    drawing_path: Path,
    *,
    total_run_time: float = DEFAULT_RUN_TIME,
    hold_time: float = DEFAULT_HOLD_TIME,
    animation_sequence: list[str] | None = None,
    page_sequences: dict[int, list[int]] | None = None,
) -> str:
    if not drawing_path.is_file():
        raise FileNotFoundError(f"Drawing not found: {drawing_path}")
    suffix = drawing_path.suffix.lower()
    if suffix not in (".svg", ".excalidraw", ".json"):
        raise ValueError("Expected .svg or .excalidraw file")

    p = _esc_path(drawing_path)
    seq_literal = repr(list(animation_sequence or []))
    pages = describe_drawing_animation_units(drawing_path) if suffix == ".svg" else []
    catalog = _format_unit_catalog(pages)
    page_seq_block = _format_page_sequences(pages, page_sequences)

    catalog_block = f"\n{catalog}\n" if catalog else ""
    page_seq_comment = (
        "\n        # Reorder draw steps by editing page_sequences below (or use the Draw order UI).\n"
        if page_sequences
        else ""
    )

    code = f'''"""Excalidraw animation — generated by Manimations Studio."""

from manim import *
from excalidraw_scene import animate_excalidraw_file


class {SCENE_CLASS}(Scene):
    def construct(self):
{catalog_block}{page_seq_comment}        animate_excalidraw_file(
            self,
            "{p}",
            total_run_time={total_run_time:.2f},
            hold_time={hold_time:.2f},
            fade_out=True,
            animation_sequence={seq_literal},
            page_sequences={page_seq_block}
        )
'''
    return validate_excalidraw_scene(code)


def validate_excalidraw_scene(code: str) -> str:
    code = code.strip()
    if code.startswith("```"):
        code = re.sub(r"^```(?:python)?\n?", "", code)
        code = re.sub(r"\n?```$", "", code)
    if f"class {SCENE_CLASS}" not in code:
        raise ValueError(f"Scene must define {SCENE_CLASS}")
    try:
        ast.parse(code)
    except SyntaxError as exc:
        raise ValueError(f"Syntax error: {exc}") from exc
    return code + ("\n" if not code.endswith("\n") else "")
