"""Compile uploaded Excalidraw/SVG into ExcalidrawScene Manim code."""

from __future__ import annotations

import ast
import re
from pathlib import Path

SCENE_CLASS = "ExcalidrawScene"
DEFAULT_RUN_TIME = 7.0
DEFAULT_HOLD_TIME = 1.25


def _esc_path(path: Path) -> str:
    return str(path.resolve()).replace("\\", "\\\\")


def starter_excalidraw_scene() -> str:
    return f'''"""Excalidraw animation — generated by Manimations Studio."""

from manim import *


class {SCENE_CLASS}(Scene):
    def construct(self):
        self.camera.background_color = BLACK
        hint = Text("Upload Excalidraw SVG and click Generate", color=WHITE, font_size=32)
        self.play(FadeIn(hint), run_time=0.8)
        self.wait(2.0)
        self.play(FadeOut(hint), run_time=0.6)
'''


def compile_excalidraw_scene(
    drawing_path: Path,
    *,
    total_run_time: float = DEFAULT_RUN_TIME,
    hold_time: float = DEFAULT_HOLD_TIME,
    animation_sequence: list[str] | None = None,
) -> str:
    if not drawing_path.is_file():
        raise FileNotFoundError(f"Drawing not found: {drawing_path}")
    suffix = drawing_path.suffix.lower()
    if suffix not in (".svg", ".excalidraw", ".json"):
        raise ValueError("Expected .svg or .excalidraw file")

    p = _esc_path(drawing_path)
    seq_literal = repr(list(animation_sequence or []))
    code = f'''"""Excalidraw animation — generated by Manimations Studio."""

from manim import *
from excalidraw_scene import animate_excalidraw_file


class {SCENE_CLASS}(Scene):
    def construct(self):
        animate_excalidraw_file(
            self,
            "{p}",
            total_run_time={total_run_time:.2f},
            hold_time={hold_time:.2f},
            fade_out=True,
            animation_sequence={seq_literal},
        )
'''
    return validate_excalidraw_scene(code)


def validate_excalidraw_scene(code: str) -> str:
    code = code.strip()
    if code.startswith("```"):
        code = re.sub(r"^```(?:python)?\n?", "", code)
        code = re.sub(r"\n?```$", "", code)
    if f"class {SCENE_CLASS}" not in code:
        raise ValueError(f"Scene must define {SCENE_CLASS}")
    try:
        ast.parse(code)
    except SyntaxError as exc:
        raise ValueError(f"Syntax error: {exc}") from exc
    return code + ("\n" if not code.endswith("\n") else "")
