"""Voice motion pipeline: transcribe audio → motion plan → Manim scene code."""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path
from typing import Any

MANIM_ROOT = Path(__file__).resolve().parents[3]
VOICE_MOTION_SKILL = MANIM_ROOT / ".cursor/skills/manim-video/voice-motion.md"
SCENE_CLASS = "VoiceMotionScene"
MAX_PLAN_SEGMENTS = 25
FORBIDDEN_IMPORTS = (
    "beat_helpers",
    "icon_library",
    "visual_resolver",
    "visual_library",
    "beat_interpreter",
)
FORBIDDEN_NAMES = ("BeatScene", "IconMobject", "ImageMobject")


def load_voice_motion_skill() -> str:
    if VOICE_MOTION_SKILL.is_file():
        return VOICE_MOTION_SKILL.read_text(encoding="utf-8")
    return "Generate VoiceMotionScene with BLACK background and WHITE Text."


def starter_voice_motion_scene() -> str:
    return '''"""Voice motion scene — generated by Manimations Studio."""

from manim import *


class VoiceMotionScene(Scene):
    def construct(self):
        self.camera.background_color = BLACK
        hint = Text("Upload narration and click Generate", color=WHITE, font_size=36)
        self.play(FadeIn(hint), run_time=1.0)
        self.wait(2.0)
        self.play(FadeOut(hint), run_time=0.8)
'''


def _transcription_to_dict(transcription: Any) -> dict[str, Any]:
    if hasattr(transcription, "model_dump"):
        return transcription.model_dump()
    if isinstance(transcription, dict):
        return transcription
    return {"text": str(transcription), "segments": []}


def transcribe_audio(openai_client: Any, audio_path: Path) -> dict[str, Any]:
    with audio_path.open("rb") as handle:
        raw = openai_client.audio.transcriptions.create(
            model="whisper-1",
            file=handle,
            response_format="verbose_json",
            timestamp_granularities=["segment"],
        )
    data = _transcription_to_dict(raw)
    segments: list[dict[str, Any]] = []
    for seg in data.get("segments") or []:
        if isinstance(seg, dict):
            start = float(seg.get("start", 0))
            end = float(seg.get("end", start))
            text = str(seg.get("text", "")).strip()
        else:
            start = float(getattr(seg, "start", 0))
            end = float(getattr(seg, "end", start))
            text = str(getattr(seg, "text", "")).strip()
        if text:
            segments.append({"start": round(start, 2), "end": round(end, 2), "text": text})
    duration = float(data.get("duration") or (segments[-1]["end"] if segments else 0))
    transcript = str(data.get("text") or " ".join(s["text"] for s in segments)).strip()
    return {
        "transcript": transcript,
        "duration_sec": round(duration, 2),
        "segments": normalize_segments(segments),
    }


def normalize_segments(segments: list[dict[str, Any]], max_segments: int = MAX_PLAN_SEGMENTS) -> list[dict[str, Any]]:
    if len(segments) <= max_segments:
        return segments
    merged: list[dict[str, Any]] = []
    bucket: list[dict[str, Any]] = []
    target = len(segments) / max_segments
    count = 0.0
    for seg in segments:
        bucket.append(seg)
        count += 1
        if count >= target and len(merged) < max_segments - 1:
            merged.append(_merge_segment_bucket(bucket))
            bucket = []
            count = 0.0
    if bucket:
        if merged:
            merged[-1] = _merge_segment_bucket([merged[-1], *bucket])
        else:
            merged.append(_merge_segment_bucket(bucket))
    return merged[:max_segments]


def _merge_segment_bucket(bucket: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "start": bucket[0]["start"],
        "end": bucket[-1]["end"],
        "text": " ".join(s["text"] for s in bucket).strip(),
    }


def build_motion_plan(openai_client: Any, model: str, segments: list[dict[str, Any]], transcript: str) -> list[dict[str, Any]]:
    payload = json.dumps({"transcript": transcript, "segments": segments}, indent=2)
    system = (
        "You plan motion-graphics visuals for a Manim voice-over video. "
        "Return JSON: {\"motion_plan\": [{\"start\", \"end\", \"narration\", \"visuals\": [str], "
        "\"mobjects\": [str]}]}. One plan item per segment. "
        "visuals = short animation instructions; mobjects = Manim classes to use. "
        "No cards, icons, or external images."
    )
    response = openai_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": f"Plan visuals for these timed segments:\n{payload}"},
        ],
        response_format={"type": "json_object"},
        temperature=0.4,
    )
    raw = response.choices[0].message.content or "{}"
    data = json.loads(raw)
    plan = data.get("motion_plan") or data.get("segments") or []
    if not isinstance(plan, list):
        return []
    out: list[dict[str, Any]] = []
    for i, item in enumerate(plan):
        if not isinstance(item, dict):
            continue
        seg = segments[i] if i < len(segments) else {}
        out.append(
            {
                "start": float(item.get("start", seg.get("start", 0))),
                "end": float(item.get("end", seg.get("end", 0))),
                "narration": str(item.get("narration") or seg.get("text") or ""),
                "visuals": list(item.get("visuals") or []),
                "mobjects": list(item.get("mobjects") or []),
            }
        )
    if not out and segments:
        for seg in segments:
            out.append(
                {
                    "start": seg["start"],
                    "end": seg["end"],
                    "narration": seg["text"],
                    "visuals": ["FadeIn white title text for narration"],
                    "mobjects": ["Text"],
                }
            )
    return out


def generate_motion_scene(
    openai_client: Any,
    model: str,
    motion_plan: list[dict[str, Any]],
    duration_sec: float,
    *,
    existing_code: str | None = None,
    edit_message: str | None = None,
) -> str:
    skill = load_voice_motion_skill()
    plan_json = json.dumps({"duration_sec": duration_sec, "motion_plan": motion_plan}, indent=2)
    user_parts = [f"Motion plan (seconds):\n{plan_json}"]
    if existing_code and edit_message:
        user_parts.append(f"Current scene code:\n```python\n{existing_code}\n```")
        user_parts.append(f"Edit request: {edit_message}")
    else:
        user_parts.append("Generate the complete VoiceMotionScene Python file.")
    response = openai_client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": skill + "\n\nReturn JSON: {\"code\": \"...full python...\"}"},
            {"role": "user", "content": "\n\n".join(user_parts)},
        ],
        response_format={"type": "json_object"},
        temperature=0.35,
    )
    raw = response.choices[0].message.content or "{}"
    data = json.loads(raw)
    code = str(data.get("code") or "")
    if not code.strip():
        raise ValueError("LLM returned empty scene code")
    return sanitize_motion_scene(code)


def sanitize_motion_scene(code: str) -> str:
    code = code.strip()
    if code.startswith("```"):
        code = re.sub(r"^```(?:python)?\n?", "", code)
        code = re.sub(r"\n?```$", "", code)
    issues = validate_motion_scene(code)
    if issues:
        raise ValueError("; ".join(issues[:3]))
    if f"class {SCENE_CLASS}" not in code:
        code = code.replace("class GeneratedScene", f"class {SCENE_CLASS}")
    if "from manim import" not in code:
        code = "from manim import *\n\n" + code
    return code + ("\n" if not code.endswith("\n") else "")


def validate_motion_scene(code: str) -> list[str]:
    issues: list[str] = []
    for forbidden in FORBIDDEN_IMPORTS:
        if forbidden in code:
            issues.append(f"Forbidden import/module: {forbidden}")
    for name in FORBIDDEN_NAMES:
        if name in code:
            issues.append(f"Forbidden symbol: {name}")
    if "class " not in code or "construct" not in code:
        issues.append("Scene must define a class with construct()")
    try:
        tree = ast.parse(code)
    except SyntaxError as exc:
        issues.append(f"Syntax error: {exc}")
        return issues
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            for forbidden in FORBIDDEN_IMPORTS:
                if forbidden in (node.module or ""):
                    issues.append(f"Forbidden import: {node.module}")
    return issues


def run_director_codegen(director_plan: dict[str, Any]) -> str:
    """Compile an approved director storyboard into VoiceMotionScene code."""
    from app.voice_codegen import compile_and_validate

    return compile_and_validate(director_plan)


def run_voice_pipeline(
    openai_client: Any,
    model: str,
    audio_path: Path,
    *,
    existing_code: str | None = None,
    edit_message: str | None = None,
    skip_transcribe: bool = False,
    existing_voice: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if skip_transcribe and existing_voice:
        transcript_data = {
            "transcript": existing_voice.get("transcript", ""),
            "duration_sec": existing_voice.get("duration_sec", 0),
            "segments": existing_voice.get("segments") or [],
        }
    else:
        transcript_data = transcribe_audio(openai_client, audio_path)
    motion_plan = build_motion_plan(
        openai_client,
        model,
        transcript_data["segments"],
        transcript_data["transcript"],
    )
    code = generate_motion_scene(
        openai_client,
        model,
        motion_plan,
        float(transcript_data["duration_sec"] or 0),
        existing_code=existing_code,
        edit_message=edit_message,
    )
    return {
        **transcript_data,
        "motion_plan": motion_plan,
        "code": code,
    }


def edit_motion_scene(
    openai_client: Any,
    model: str,
    project: dict[str, Any],
    edit_message: str,
    existing_code: str,
) -> dict[str, Any]:
    voice = project.get("voice_motion") or {}
    motion_plan = voice.get("motion_plan") or []
    duration = float(voice.get("duration_sec") or 0)
    code = generate_motion_scene(
        openai_client,
        model,
        motion_plan,
        duration,
        existing_code=existing_code,
        edit_message=edit_message,
    )
    return {"code": code, "message": "Updated motion scene from your edit."}
